// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PharmacyChainsManagementBE.Models;

#nullable disable

namespace PharmacyChainsManagementBE.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    [Migration("20260718141902_AddUserProfileFields")]
    partial class AddUserProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.AuditLog", b =>
                {
                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.HasKey("AuditId")
                        .HasName("PK__AUDIT_LO__5AF33E33EA16EB9D");

                    b.HasIndex("ActorId");

                    b.ToTable("AUDIT_LOG");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Branch", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("branch_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("BranchId")
                        .HasName("PK__BRANCH__E55E37DE2FFC4385");

                    b.ToTable("BRANCH");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Inventory", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_on_hand");

                    b.Property<int>("SafetyStockLevel")
                        .HasColumnType("integer")
                        .HasColumnName("safety_stock_level");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InventoryId")
                        .HasName("PK__INVENTOR__B59ACC4968023E2D");

                    b.HasIndex("BatchId");

                    b.HasIndex("MedicineId");

                    b.HasIndex(new[] { "BranchId", "BatchId" }, "UQ_INVENTORY_BranchBatch")
                        .IsUnique();

                    b.ToTable("INVENTORY");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_code");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_status");

                    b.Property<Guid?>("PrescriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InvoiceId")
                        .HasName("PK__INVOICE__F58DFD49258ACF2C");

                    b.HasIndex("BranchId");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("StaffId");

                    b.HasIndex(new[] { "InvoiceCode" }, "UQ__INVOICE__5ED70A35B0ECDDDB")
                        .IsUnique();

                    b.ToTable("INVOICE");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.InvoiceDetail", b =>
                {
                    b.Property<Guid>("InvoiceDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_detail_id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("InvoiceDetailId")
                        .HasName("PK__INVOICE___84908DB6027EFE8E");

                    b.HasIndex("BatchId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("MedicineId");

                    b.ToTable("INVOICE_DETAIL");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Medicine", b =>
                {
                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("medicine_name");

                    b.Property<decimal>("StandardPrice")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("standard_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsageDescription")
                        .HasColumnType("text")
                        .HasColumnName("usage_description");

                    b.HasKey("MedicineId")
                        .HasName("PK__MEDICINE__E7148EBBD592791F");

                    b.ToTable("MEDICINE");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.MedicineBatch", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("batch_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<DateOnly?>("ManufacturingDate")
                        .HasColumnType("date")
                        .HasColumnName("manufacturing_date");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<string>("QcStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("qc_status");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("BatchId")
                        .HasName("PK__MEDICINE__DBFC0431E550911D");

                    b.HasIndex("SupplierId");

                    b.HasIndex(new[] { "MedicineId", "BatchNumber" }, "UQ_MEDICINE_BATCH_Number")
                        .IsUnique();

                    b.ToTable("MEDICINE_BATCH");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.PaymentGateway", b =>
                {
                    b.Property<short>("GatewayId")
                        .HasColumnType("smallint")
                        .HasColumnName("gateway_id");

                    b.Property<string>("GatewayCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gateway_code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.HasKey("GatewayId")
                        .HasName("PK__PAYMENT___0AF5B00B3EAC3274");

                    b.HasIndex(new[] { "GatewayCode" }, "UQ__PAYMENT___3AC42EB5324B5E97")
                        .IsUnique();

                    b.ToTable("PAYMENT_GATEWAY");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short?>("GatewayId")
                        .HasColumnType("smallint")
                        .HasColumnName("gateway_id");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("gateway_reference");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PaymentId")
                        .HasName("PK__PAYMENT___ED1FC9EA5BA1EC89");

                    b.HasIndex("GatewayId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("PAYMENT_TRANSACTION");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Prescription", b =>
                {
                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("customer_name");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("doctor_name");

                    b.Property<DateOnly>("PrescriptionDate")
                        .HasColumnType("date")
                        .HasColumnName("prescription_date");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PrescriptionId")
                        .HasName("PK__PRESCRIP__3EE444F81A0DC9F6");

                    b.HasIndex("BranchId");

                    b.HasIndex("StaffId");

                    b.ToTable("PRESCRIPTION");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.PrescriptionDetail", b =>
                {
                    b.Property<Guid>("PrescriptionDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_detail_id");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dosage");

                    b.Property<string>("Duration")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("duration");

                    b.Property<string>("Frequency")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("frequency");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("PrescriptionDetailId")
                        .HasName("PK__PRESCRIP__CD190C8BB0BF34DD");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PRESCRIPTION_DETAIL");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.PurchaseOrder", b =>
                {
                    b.Property<Guid>("PoId")
                        .HasColumnType("uuid")
                        .HasColumnName("po_id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("ExpectedDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_date");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<string>("PoStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("po_status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PoId")
                        .HasName("PK__PURCHASE__368DA7F09A44F7AA");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SupplierId");

                    b.ToTable("PURCHASE_ORDER");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<Guid>("PoDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("po_detail_id");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<int>("OrderedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("ordered_quantity");

                    b.Property<Guid>("PoId")
                        .HasColumnType("uuid")
                        .HasColumnName("po_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("PoDetailId")
                        .HasName("PK__PURCHASE__9E6103B2CC7E0FEF");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PoId");

                    b.ToTable("PURCHASE_ORDER_DETAIL");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileUri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_uri");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<Guid>("GeneratedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_by");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("report_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ReportId")
                        .HasName("PK__REPORT__779B7C58AB9D0C61");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("REPORT");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Role", b =>
                {
                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_code");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__ROLE__760965CC18C3E6A4");

                    b.HasIndex(new[] { "RoleCode" }, "UQ__ROLE__BAE6307522F2B53F")
                        .IsUnique();

                    b.ToTable("ROLE");

                    b.HasData(
                        new
                        {
                            RoleId = (short)1,
                            IsActive = true,
                            RoleCode = "BUSINESS_ADMIN",
                            RoleName = "Business Admin"
                        },
                        new
                        {
                            RoleId = (short)2,
                            IsActive = true,
                            RoleCode = "BRANCH_MANAGER",
                            RoleName = "Branch Manager"
                        },
                        new
                        {
                            RoleId = (short)3,
                            IsActive = true,
                            RoleCode = "STAFF",
                            RoleName = "Staff"
                        },
                        new
                        {
                            RoleId = (short)4,
                            IsActive = true,
                            RoleCode = "INVENTORY_MANAGER",
                            RoleName = "Inventory Manager"
                        });
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.StockTransfer", b =>
                {
                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateOnly?>("ApprovedDate")
                        .HasColumnType("date")
                        .HasColumnName("approved_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_branch_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("RequestDate")
                        .HasColumnType("date")
                        .HasColumnName("request_date");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<Guid>("ToBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_branch_id");

                    b.Property<string>("TransferStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("transfer_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TransferId")
                        .HasName("PK__STOCK_TR__78E6FD33FAF72D38");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("FromBranchId");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("ToBranchId");

                    b.ToTable("STOCK_TRANSFER");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.StockTransferDetail", b =>
                {
                    b.Property<Guid>("TransferDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_detail_id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.HasKey("TransferDetailId")
                        .HasName("PK__STOCK_TR__EC2B8CDB86128AC6");

                    b.HasIndex("BatchId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("TransferId");

                    b.ToTable("STOCK_TRANSFER_DETAIL");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Supplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("supplier_name");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SupplierId")
                        .HasName("PK__SUPPLIER__6EE594E8CCD9CE8A");

                    b.ToTable("SUPPLIER");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfilePhotoUri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile_photo_uri");

                    b.Property<DateTimeOffset?>("ResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("PK__USER__B9BE370FD5688795");

                    b.HasIndex("BranchId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_User_IsDeleted_Filtered")
                        .HasFilter("\"is_deleted\" = false");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__USER__AB6E6164A2B157E7")
                        .IsUnique();

                    b.ToTable("USER");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4046),
                            Email = "businessadmin@pharmacy.com",
                            FullName = "Admin User",
                            IsDeleted = false,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$IYQJvf0r3oqJXCtfmuNC.ut.sFypUr1LtCajqdfXki2WAbbAu3p4a",
                            RoleId = (short)1,
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4049)
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4055),
                            Email = "manager@pharmacy.com",
                            FullName = "Manager User",
                            IsDeleted = false,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$IYQJvf0r3oqJXCtfmuNC.ut.sFypUr1LtCajqdfXki2WAbbAu3p4a",
                            RoleId = (short)2,
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4056)
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4063),
                            Email = "staff@pharmacy.com",
                            FullName = "Staff User",
                            IsDeleted = false,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$IYQJvf0r3oqJXCtfmuNC.ut.sFypUr1LtCajqdfXki2WAbbAu3p4a",
                            RoleId = (short)3,
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4064)
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4068),
                            Email = "inventory@pharmacy.com",
                            FullName = "Inventory Manager",
                            IsDeleted = false,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$IYQJvf0r3oqJXCtfmuNC.ut.sFypUr1LtCajqdfXki2WAbbAu3p4a",
                            RoleId = (short)4,
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4069)
                        },
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111112"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4072),
                            Email = "businessadmin2@pharmacy.com",
                            FullName = "Admin User 2",
                            IsDeleted = false,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$IYQJvf0r3oqJXCtfmuNC.ut.sFypUr1LtCajqdfXki2WAbbAu3p4a",
                            RoleId = (short)1,
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4074)
                        },
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111113"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4077),
                            Email = "businessadmin3@pharmacy.com",
                            FullName = "Admin User 3",
                            IsDeleted = false,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$IYQJvf0r3oqJXCtfmuNC.ut.sFypUr1LtCajqdfXki2WAbbAu3p4a",
                            RoleId = (short)1,
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4078)
                        },
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111114"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4082),
                            Email = "businessadmin4@pharmacy.com",
                            FullName = "Admin User 4",
                            IsDeleted = false,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$IYQJvf0r3oqJXCtfmuNC.ut.sFypUr1LtCajqdfXki2WAbbAu3p4a",
                            RoleId = (short)1,
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4083)
                        },
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111115"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4087),
                            Email = "businessadmin5@pharmacy.com",
                            FullName = "Admin User 5",
                            IsDeleted = false,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$IYQJvf0r3oqJXCtfmuNC.ut.sFypUr1LtCajqdfXki2WAbbAu3p4a",
                            RoleId = (short)1,
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 7, 18, 14, 18, 59, 378, DateTimeKind.Utc).AddTicks(4088)
                        });
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.UserSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("PK__USER_SES__session_id");

                    b.HasIndex("RefreshToken");

                    b.HasIndex("UserId");

                    b.ToTable("USER_SESSION");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.AuditLog", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.User", "Actor")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorId")
                        .IsRequired()
                        .HasConstraintName("FK_AUD_ACTOR");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Inventory", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.MedicineBatch", "Batch")
                        .WithMany("Inventories")
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK_INV_BATCH");

                    b.HasOne("PharmacyChainsManagementBE.Models.Branch", "Branch")
                        .WithMany("Inventories")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_INV_BRANCH");

                    b.HasOne("PharmacyChainsManagementBE.Models.Medicine", "Medicine")
                        .WithMany("Inventories")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_INV_MEDICINE");

                    b.Navigation("Batch");

                    b.Navigation("Branch");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Invoice", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.Branch", "Branch")
                        .WithMany("Invoices")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_INV_BRANCH_2");

                    b.HasOne("PharmacyChainsManagementBE.Models.Prescription", "Prescription")
                        .WithMany("Invoices")
                        .HasForeignKey("PrescriptionId")
                        .HasConstraintName("FK_INV_PRESCRIPTION");

                    b.HasOne("PharmacyChainsManagementBE.Models.User", "Staff")
                        .WithMany("Invoices")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_INV_STAFF");

                    b.Navigation("Branch");

                    b.Navigation("Prescription");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.InvoiceDetail", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.MedicineBatch", "Batch")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK_INVD_BATCH");

                    b.HasOne("PharmacyChainsManagementBE.Models.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_INVD_INVOICE");

                    b.HasOne("PharmacyChainsManagementBE.Models.Medicine", "Medicine")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_INVD_MEDICINE");

                    b.Navigation("Batch");

                    b.Navigation("Invoice");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.MedicineBatch", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.Medicine", "Medicine")
                        .WithMany("MedicineBatches")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_BATCH_MEDICINE");

                    b.HasOne("PharmacyChainsManagementBE.Models.Supplier", "Supplier")
                        .WithMany("MedicineBatches")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK_BATCH_SUPPLIER");

                    b.Navigation("Medicine");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.PaymentTransaction", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.PaymentGateway", "Gateway")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("GatewayId")
                        .HasConstraintName("FK_PAY_GATEWAY");

                    b.HasOne("PharmacyChainsManagementBE.Models.Invoice", "Invoice")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_PAY_INVOICE");

                    b.Navigation("Gateway");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Prescription", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.Branch", "Branch")
                        .WithMany("Prescriptions")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_PRES_BRANCH");

                    b.HasOne("PharmacyChainsManagementBE.Models.User", "Staff")
                        .WithMany("Prescriptions")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_PRES_STAFF");

                    b.Navigation("Branch");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.PrescriptionDetail", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.Medicine", "Medicine")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_PRESD_MEDICINE");

                    b.HasOne("PharmacyChainsManagementBE.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("PrescriptionId")
                        .IsRequired()
                        .HasConstraintName("FK_PRESD_PRESCRIPTION");

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.PurchaseOrder", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.User", "ApprovedByNavigation")
                        .WithMany("PurchaseOrderApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_PO_APPROVED_BY");

                    b.HasOne("PharmacyChainsManagementBE.Models.Branch", "Branch")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_PO_BRANCH");

                    b.HasOne("PharmacyChainsManagementBE.Models.User", "CreatedByNavigation")
                        .WithMany("PurchaseOrderCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_PO_CREATED_BY");

                    b.HasOne("PharmacyChainsManagementBE.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK_PO_SUPPLIER");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Branch");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.Medicine", "Medicine")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_POD_MEDICINE");

                    b.HasOne("PharmacyChainsManagementBE.Models.PurchaseOrder", "Po")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PoId")
                        .IsRequired()
                        .HasConstraintName("FK_POD_PO");

                    b.Navigation("Medicine");

                    b.Navigation("Po");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Report", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.User", "GeneratedByNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("GeneratedBy")
                        .IsRequired()
                        .HasConstraintName("FK_REP_GENERATED_BY");

                    b.Navigation("GeneratedByNavigation");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.StockTransfer", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.User", "ApprovedByNavigation")
                        .WithMany("StockTransferApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_ST_APPROVED_BY");

                    b.HasOne("PharmacyChainsManagementBE.Models.Branch", "FromBranch")
                        .WithMany("StockTransferFromBranches")
                        .HasForeignKey("FromBranchId")
                        .IsRequired()
                        .HasConstraintName("FK_ST_FROM_BRANCH");

                    b.HasOne("PharmacyChainsManagementBE.Models.User", "RequestedByNavigation")
                        .WithMany("StockTransferRequestedByNavigations")
                        .HasForeignKey("RequestedBy")
                        .IsRequired()
                        .HasConstraintName("FK_ST_REQUESTED_BY");

                    b.HasOne("PharmacyChainsManagementBE.Models.Branch", "ToBranch")
                        .WithMany("StockTransferToBranches")
                        .HasForeignKey("ToBranchId")
                        .IsRequired()
                        .HasConstraintName("FK_ST_TO_BRANCH");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("FromBranch");

                    b.Navigation("RequestedByNavigation");

                    b.Navigation("ToBranch");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.StockTransferDetail", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.MedicineBatch", "Batch")
                        .WithMany("StockTransferDetails")
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK_STD_BATCH");

                    b.HasOne("PharmacyChainsManagementBE.Models.Medicine", "Medicine")
                        .WithMany("StockTransferDetails")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_STD_MEDICINE");

                    b.HasOne("PharmacyChainsManagementBE.Models.StockTransfer", "Transfer")
                        .WithMany("StockTransferDetails")
                        .HasForeignKey("TransferId")
                        .IsRequired()
                        .HasConstraintName("FK_STD_TRANSFER");

                    b.Navigation("Batch");

                    b.Navigation("Medicine");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.User", b =>
                {
                    b.HasOne("PharmacyChainsManagementBE.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK_USER_BRANCH");

                    b.HasOne("PharmacyChainsManagementBE.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLE");

                    b.Navigation("Branch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Branch", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Invoices");

                    b.Navigation("Prescriptions");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("StockTransferFromBranches");

                    b.Navigation("StockTransferToBranches");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Medicine", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InvoiceDetails");

                    b.Navigation("MedicineBatches");

                    b.Navigation("PrescriptionDetails");

                    b.Navigation("PurchaseOrderDetails");

                    b.Navigation("StockTransferDetails");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.MedicineBatch", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InvoiceDetails");

                    b.Navigation("StockTransferDetails");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.PaymentGateway", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Prescription", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("PrescriptionDetails");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.StockTransfer", b =>
                {
                    b.Navigation("StockTransferDetails");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.Supplier", b =>
                {
                    b.Navigation("MedicineBatches");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("PharmacyChainsManagementBE.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Invoices");

                    b.Navigation("Prescriptions");

                    b.Navigation("PurchaseOrderApprovedByNavigations");

                    b.Navigation("PurchaseOrderCreatedByNavigations");

                    b.Navigation("Reports");

                    b.Navigation("StockTransferApprovedByNavigations");

                    b.Navigation("StockTransferRequestedByNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
